Add reviews
SugarFoxy/java-filmorate pull request #15
Opened 2022-12-10 22:59 UTC by RoketV

Доделал всё, кроме тестов. Ещё по ходу нужно вернуть таблицы user_like и user_dislike.

В общем, как реализовано здесь всё:

Есть абстрактный класс Review, у него есть три поля только основных. От него идёт класс FilmReview, там уже добавляются ссылки на User и Film.

Часть логики, например по лайкам, кочует в сервис из БД. 

Контроллер получает какой-то data transfer object, который немного (не так сильно, как я в начале думал) отличается от модели и преобразует через mapper его в model. Так как в MVC контроллер отвечает за передачу данных на фронт данных, поэтому он работает с dto только. Остальные слои работают с моделью. Короче, говоря, dto здесь больше для понту вышло, так как заговорили об этом паттерне в начале.

Контроллер, по best practise, которую вычитал на сайте baeldung, отдаёт ResponseEntity, а не model. Так удобнее запихивать туда какие-то сразу headers и прочее.

Тесты ещё не готовы. Кое-где нужно провести рефакторинг. В общем, прошу на суд)

2022-12-11 14:49 UTC, SugarFoxy requested changes
Все превосходно, ты проделал большую работу. Единственное убери логику из контролера и реализуй тесты)))

2022-12-11 14:49 UTC, SugarFoxy commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ReviewController.java
> +            Set<FilmReviewDto> reviews = reviewsService.getFilmReviews(filmId.get(), count)
Насколько я знаю в контролере не должно быть логики. Сортировка и так далее это часть бизнес логики лучше перенести ее в сервис.

2022-12-12 09:35 UTC, Sad-Duck commented on src/main/resources/data.sql
> +
понятно, что это фигня, но тут в файле много пропусков строк стало, может чуть-чуть подредактировать?)

2022-12-12 09:37 UTC, Sad-Duck commented on src/main/java/ru/yandex/practicum/filmorate/dto/FilmReviewDto.java
> +
и тут тоже лишний пропуск бросается в глаза:)

2022-12-12 09:38 UTC, Sad-Duck commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ReviewController.java
> +
и тут ещё

2022-12-12 21:22 UTC, SugarFoxy approved these changes

2022-12-12 22:07 UTC, SugarFoxy approved these changes

2022-12-12 22:07 UTC, Sad-Duck approved these changes

2022-12-12 22:08 UTC, merged