Develop
SugarFoxy/java-filmorate pull request #17
Opened 2022-12-13 19:48 UTC by SugarFoxy

2022-12-14 20:30 UTC, LexLippi requested changes
Привет!

Работа очень хорошая, но хочу обратить внимание на то, что замечания, которые я оставил в коде общие, и если кто-то увидит, что я оставил такое замечание в его участке кода, но не оставил у другого участника, то надо сообщить ему, чтобы он тоже это переделал.

Ещё важный момент о договоренностях. Чаще всего стоит договариваться о подходах, которые вы используете. Лучше делать это формально в README репозитория, чтобы всегда можно было на это сослаться или ввести новых участников в курс дела.

Каких-то глобальных проблем я не нашёл. За исключением странного подхода при работе с `JdbcTemplate`.

 Желаю удачи при доработке замечаний!!!

2022-12-14 20:30 UTC, LexLippi commented on README.md
>  # java-filmorate
Хорошо бы в `README` было описать какие пункты из ТЗ вы сделали, чтобы я не гадал, что было набрано 18 сторипоинтов, а мог легко это сверить с тем, что описано в `README`

2022-12-14 20:30 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public List<Film> getFilmsByDirector(@PathVariable int directorId, @RequestParam String sortBy) {
Лучше в качестве параметра `sortBy` использовать перечисление (`enum`). 
1. Это гарантирует, что мы можем провалидировать входной параметр для сортировки
2. С перечислением удобнее работать внутри своего кода
3. Сравнение перечислений работает быстрее, чем сравнение строк

2022-12-14 20:30 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +            for (ObjectError error : bindingResult.getAllErrors()) {
Можно использовать `var`

2022-12-14 20:30 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    public void logValidationErrors(BindingResult bindingResult) {
Есть объяснения почему этот метод находится в компоненте сервис?
Концептуально, я не против, но хочется понять почему именно здесь

2022-12-14 20:30 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/director/DirectorStorage.java
> +    Director updateDirector(Director director);
Не вижу большого смысла возвращать из этих методов объект `Director`, но если есть сильное желание, то можно и так.

2022-12-14 20:30 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +    private int id;
Идентиикатор должен быть строго больше нуля, стоит навесить на него валидирующую аннотацию тоже

2022-12-14 20:30 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/utils/director/DirectorUtils.java
> +}
Зачем для этого заводить отдельный класс? Почему бы не реализовать это внутри `DirectorStorage`?

2022-12-14 20:30 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/director/impl/DirectorDbStorage.java
> +        SqlRowSet directorRows = jdbcTemplate.queryForRowSet(sqlQuery);
Почему не воспользоваться методом `query` или `queryForList`?

2022-12-14 20:30 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/director/impl/DirectorDbStorage.java
> +public class DirectorDbStorage implements DirectorStorage {
Общий вопрос к этому и другим классам: почему бы не пользоваться специализированными методами класса `JdbcTemplate`, чтобы получать сразу объект, а не `SqlRowSet`?

Там, где вывод типа очевиден можно использовать `var`, а не прописывать тип явно

2022-12-14 20:30 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ReviewController.java
> +public class ReviewController {
Стоит выработать общий подход и везде использовать либо аннотацию `Autowired`, либо `RequiredArgsConstructor`.

Аналогично следует выработать стратегию касательно того, что мы возвращаем из методов маппинга в контроллере: объекты или `ResponseEntity`.

Тоже самое касается и использования `dto` и моделей.

Зоопарк подходов в рамках одного проекта - не лучшая идея. Потому что поддерживать такой код на ровном месте становится очень затратно

2022-12-14 20:30 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private int id;
Валидацию добавить

2022-12-14 20:30 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/FilmReview.java
> +public class FilmReview extends Review {
Честно, не очень понятно зачем нужен такой сложный объект. 
1. Почему нельзя обойтись просто объектом, содержащим идентификаторы данных сущностей?
2. Непонятно, какое преимущество нам дает использование наследования в данном контексте. У нас есть отзывы не на фильм? Непонятно, что значит базовый класс Отзыв.

2022-12-14 20:30 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int id;
Валидация

2022-12-14 20:30 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/FeedEvent.java
> +public class FeedEvent {
По опыту скажу, что лучше не использовать суффикс `Event`, за исключением некоторых специфичных случаев. Это слишком общее понятие, и оно лишь напрасно засоряет код дополнительной когнитивной нагрузкой.

2022-12-14 20:30 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/FeedEvent.java
> +    }
У любого объекта и так есть подобный публичный конструктор, сгенерированный автоматически. Его имеет смысл объявлять только, если делать его приватным.

Да, и в данном контексте - это выглядит скорее, как нарушение логики работы.Создание пустой новости.

2022-12-14 20:30 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FeedEventService.java
> +                log.trace("{}: {}", event.getClass(), objectMapper.writeValueAsString(event));
Для целей логгирования лучше переопределить у объекта метод `toString()`, поскольку чаще всего достаточно логгировать не все поля объекта, а часть, или надо сделать формат вывода более читаемым, чем просто JSON/

2022-12-14 20:30 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FeedEventService.java
> +    public void setObjectMapper(ObjectMapper objectMapper) {
Зачем отдельный метод?
Почему не проинициализировать в конструкторе?

2022-12-14 20:30 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dto/FilmReviewDto.java
> +import com.fasterxml.jackson.annotation.JsonProperty;
Лишний импорт

2022-12-14 20:30 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/reviews/impl/ReviewsDbStorage.java
> +        String sql = "SELECT REVIEW_ID FROM REVIEW_MODEL LIMIT ?";
Лучше использовать оператор `FETCH`, поскольку именно он задокументирован в стандарте `SQL`, а оператор `LIMIT` реализуется опционально и может быть не реализован для некоторых платформ или в некоторых версиях различных СУБД.

https://www.cybertec-postgresql.com/en/postgresql-limit-vs-fetch-first-rows-with-ties/

2022-12-14 20:30 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/film/impl/FilmDbStorage.java
> +                        "ORDER BY rate DESC";
1. Тяжеловато читать такой запрос. Стоит оставить комментарий, как он работает для других разработчиков
2. Лучше не использовать цифры в названии таблиц/переменных etc.
3. Кажется можно было бы обойтись запросом попроще, но без комментария сложно в этом разобраться наверняка

2022-12-14 20:30 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/film/impl/FilmDbStorage.java
> +                        "WHERE LOWER(fm.title) LIKE LOWER('%'||?||'%') " +
Лучше использовать оператор `ilike`

2022-12-14 20:30 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/film/impl/FilmDbStorage.java
> +            case "director,title":
1. Почему в этом случае не совершаем никаких действий?
2. Почему нет оператора break?

2022-12-14 20:30 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/film/impl/FilmDbStorage.java
> +    public List<Film> searchFilm(String query, String searchBy) {
Пояснения к запросам не помешали бы

2022-12-14 20:30 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/event/impl/FeedEventDbStorage.java
> +        cacheEventTypes();
А если при старте приложения для некоторых элементов перечисления будут не заполнены данные в БД?
Получается, что при добавлении их в БД, мы не сможем с ними корректно работать?

Тогда надо либо гарантировать, что они есть в БД на уровне миграции и здесь оставить коментарий, что это гарантируется, либо проверять состояние данных каждый раз, когда это необходимо.

2022-12-15 03:39 UTC, SugarFoxy commented on src/main/java/ru/yandex/practicum/filmorate/dao/director/impl/DirectorDbStorage.java
> +        SqlRowSet directorRows = jdbcTemplate.queryForRowSet(sqlQuery);
В обучающем курсе, подробно описан был только этот метод. Поэтому большинство людей решали - так. Переделывать нет времени

2022-12-15 06:38 UTC, mic-uglov commented on src/main/java/ru/yandex/practicum/filmorate/model/FeedEvent.java
> +public class FeedEvent {
Кажется, это прямо классический event - рассылается, прослушивается

2022-12-15 06:41 UTC, mic-uglov commented on src/main/java/ru/yandex/practicum/filmorate/model/FeedEvent.java
> +    }
Казалось, что такой конструктор по умолчанию есть, если нет явно объявленных конструкторов. Ошибались?

2022-12-15 06:44 UTC, mic-uglov commented on src/main/java/ru/yandex/practicum/filmorate/service/FeedEventService.java
> +                log.trace("{}: {}", event.getClass(), objectMapper.writeValueAsString(event));
Трассировка была для отладки, забыли убрать ) Убрали, чтобы не смущать

2022-12-15 06:49 UTC, mic-uglov commented on src/main/java/ru/yandex/practicum/filmorate/dao/event/impl/FeedEventDbStorage.java
> +        cacheEventTypes();
Подумали, что состав справочников, соответствующих перечислениям, определяется бизнес-логикой приложения. Нет никакого смысла их изменять без соответствущих изменений в коде. Будем гарантировать

2022-12-15 06:52 UTC, mic-uglov commented on src/main/java/ru/yandex/practicum/filmorate/service/FeedEventService.java
> +    public void setObjectMapper(ObjectMapper objectMapper) {
Потому что поле опциональное. В тестах, например, не нужно. Официальная документация spring рекомендует именно так с такими полями поступать. Ну, отладочную трассировку убрали, так что... )

2022-12-15 08:59 UTC, mic-uglov commented on src/main/java/ru/yandex/practicum/filmorate/dao/film/impl/FilmDbStorage.java
> +                        "WHERE LOWER(fm.title) LIKE LOWER('%'||?||'%') " +
Нет здесь противоречия с тем, что лучше LIMIT не использовать?

2022-12-15 10:19 UTC, LexLippi reviewed
Привет!

Работа хорошая! Оставил пару замечаний, которые можно исправить, а можно не исправлять. Отлично, что были выбраны сложные для реализации задачи. В целом, по архитектуре кода никаких вопросов нет - это отлично. Код поддается модификации и добавлении новых фич без какой-то особой боли. 

Чего мне немного не хватило изначально - это использования специализированных методов в `JdbcTemplate` и простоты запросов. Кажется, что некоторые из запросов могли бы быть немного проще, но это придёт с опытом. 

Еще хотел бы посоветовать почитать про представления в SQL - https://www.w3schools.com/sql/sql_view.asp . Они позволяют абстрагироваться от того, как выглядит таблица и спокойно делать, например, `select *`. Потому что если сейчас пользоваться таким подходом, то при добавлении новых полей в таблицу во многие `ResultSet` будут приходить лишние объекты, которые там не требуются. Также это облегчает чтение и понимание ваших запросов для других разработчиков, поскольку все selectы становятся довольно простыми, а основная сложность уходит в создание представлений.

Все молодцы! Если оставшиеся замечания переделывать нет желания, то я приму работу в таком виде!

Желаю удачи в следующих спринтах или (вдруг) при доработке этого!

2022-12-15 10:19 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +                                        @RequestParam(defaultValue = "0") int year) {
Лучше в таком случае использовать объектный аналог `int` - `Integer`, и в качестве дефолтного значения использовать `null`. Потому что 0 по каким-то причинам может оказаться осмысленным значением.

Или например `Optional`, как это использовано в другом контроллере

2022-12-15 10:19 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public List<Film> getFilmsByDirector(@PathVariable int directorId, @RequestParam("sortBy") QueryBy sortBy) {
Лучше здесь использовать отдельное перечисление, так как здесь допустимы не все значения из этого перечисления, как я понимаю.

Либо стоит проводить валидацию

2022-12-15 10:19 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/film/impl/FilmDbStorage.java
> +        // отсортированные по количеству лайков
Ок, кажется, что строки-запросы довольно сильно повторяются, поэтому можно было бы разбить их на несколько частей и конкатенировать, когда это необходимо: `base_sql`, `director_clause`, `group_by_clause` и тд.

Почему я считаю, что это лучше? Потому что если рассуждать с точки зрения поддержки и развития проекта, то эти подзапросы могут понадобиться, если будет придумана какая-то дополнительная логика. И не придется в очередной раз дублировать запрос с нуля, а надо будет воспользоваться существующими константами

2022-12-15 10:19 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/film/impl/FilmDbStorage.java
> +                throw new IllegalArgumentException("Необрабатываемый параметр searchBy - " + searchBy + ".");
И мое предыдущее замечание скорее всего позволило бы собирать запрос на ходу и не делать два вложенных `switch`. Это не проблема, но было бы приятнее динамически собирать запрос.

2022-12-16 09:13 UTC, LexLippi approved these changes
Всем привет!

Отличная работа!

Желаю удачи в следующих спринтах!!!

2022-12-16 09:13 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/sorts/StringToSearchConverter.java
> +    }
В реальных проектах такие классы чаще всего делают синглтонами.
Один из способов реализовать этот паттерн с помощью `enum`:

https://www.geeksforgeeks.org/advantages-and-disadvantages-of-using-enum-as-singleton-in-java/

2023-02-22 21:37 UTC, merged