Add friends likes
SugarFoxy/java-filmorate pull request #3
Opened 2022-10-25 19:48 UTC by SugarFoxy

2022-10-26 08:24 UTC, LexLippi requested changes
Еще зачем-то были удалены тесты. Этого не надо делать. Тесты по-прежнему должны выполняться, так как главное в нашей жизни разработчиков - это обратная совместимость :)

2022-10-26 08:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +    Map<Integer, User> getMapUsers();
А зачем тебе метод, который возвращает словарь. 
Метода получения пользователей списком должно быть достаточно. Из полученного списка при необходимости можно сделать `Map`, так что логически они ничем не отличаются

2022-10-26 08:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +    void updateUsers(User user);
`updateUser`, наверное

2022-10-26 08:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        Collection<User> value = users.values();
Не стоит заводить такую переменную. У нее даже название неинформативное, это признак того, что этот код лучше заинлайнить

2022-10-26 08:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public Map<Integer, User> getMapUsers() {
Я против этого метода впринципе, но у каждого метода интерфейса должна быть аннотация `@Override`

2022-10-26 08:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        return users.get(id);
А почему здесь и в `FilmStorage` логика разная?
Хочется какого-то единообразия.

А то в одном случае ты при отсутствии элемента ты выбрасываешь исключение, а в другом просто возвращаешь `null`

2022-10-26 08:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        Collection<Film> films1 = films.values();
Аналогично `InMemoryUserStorage`

2022-10-26 08:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    UserStorage storage;
Модификаторы доступа - `private final`

2022-10-26 08:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private UserService(InMemoryUserStorage storage) {
А почему этот конструктор приватный?

2022-10-26 08:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public User postUser(User user) {
Лучше назвать метод `createUser`

2022-10-26 08:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (storage.getMapUsers().containsKey(id)) {
Если хочется иметь эту проверку необходимо оставить её внутри, как в `FilmStorage`

2022-10-26 08:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        for (Integer idet : storage.getUserById(id).getFriends()) {
Может `friendId`?

2022-10-26 08:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (!storage.getMapUsers().containsKey(id)
Можно обойтись использованием метода `get`, который сам по себе выбрасывает `AbsenceOfObjectException`

2022-10-26 08:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User you = storage.getUserById(id);
лучше `user`

2022-10-26 08:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User you = storage.getUserById(id);
Лучше `user`

2022-10-26 08:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                    .collect(Collectors.toList());
Если пользуешься версией JDK 16 и выше, то можно `toList()`

2022-10-26 08:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                    .collect(Collectors.toList());
Можно упростить метод. 
До вызова `collect`, воспользоваться `map(userId -> storage.getUserById(userId))` и у тебя сразу будет список объектов, а не список идентификаторов

2022-10-26 08:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    FilmStorage storage;
`private final`

2022-10-26 08:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .collect(Collectors.toList());
Аналогично про `toList()`

2022-10-26 08:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        likes.add(id);
Потенциально этот метод и все методы ниже могут порождать `NullPointerException`, хотелось бы этого избежать

2022-10-26 08:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/exception/AbsenceOfObjectException.java
> +        super(massager);
Странное название

2022-10-26 08:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/handler/ErrorHandler.java
> +        Map<String, String> map = Map.of("error", e.getMessage());
Не стоит называть переменную `map`. Касается всех методов

2022-10-26 08:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/handler/ErrorHandler.java
> +        String[] allErrors = e.getAllErrors().toString().split(";");
Зачем промежуточная переменная? Если можно после `split` сразу послдений элемент попросить?

2022-10-26 08:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    UserService userService;
`private final`

2022-10-26 08:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmService service;
`private final`

2022-10-27 10:51 UTC, SugarFoxy commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private UserService(InMemoryUserStorage storage) {
потому что я дислексик и не отличаюсь внимательностью)))

2022-10-27 11:03 UTC, SugarFoxy commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                    .collect(Collectors.toList());
спасибо запомню

2022-10-27 11:07 UTC, SugarFoxy commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                    .collect(Collectors.toList());
не умею стримами пользоваться, спасибо огромное за подсказки

2022-10-27 11:16 UTC, SugarFoxy commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .collect(Collectors.toList());
просят на 11 делать, пока оставлю как есть

2022-10-27 11:24 UTC, SugarFoxy commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        likes.add(id);
Я же вроде исключила эту возможность проинициализировав список в гетере

2022-10-27 11:38 UTC, SugarFoxy commented on src/main/java/ru/yandex/practicum/filmorate/controller/handler/ErrorHandler.java
> +        String[] allErrors = e.getAllErrors().toString().split(";");
не знаю как и не нашла

2022-10-27 11:41 UTC, SugarFoxy commented on src/main/java/ru/yandex/practicum/filmorate/exception/AbsenceOfObjectException.java
> +        super(massager);
да с этим у меня проблемы xD

2022-10-29 07:46 UTC, LexLippi requested changes
Привет!

Работа хорошая, особых логических замечаний больше нет. Единственное, что требуется в каком-то виде вернуть тесты, чтобы было видно, что валидация работает по-прежнему в соответствии с логикой из предыдущего спринта.

Желаю удачи!

2022-10-31 06:50 UTC, LexLippi approved these changes
Привет!

В целом хорошая работа. 
Желаю удачи в следующих спринтах

2022-11-01 15:24 UTC, merged