Add database
SugarFoxy/java-filmorate pull request #4
Opened 2022-11-24 07:08 UTC by SugarFoxy

2022-11-25 07:49 UTC, LexLippi commented
1. Файлы из директории db не надо заливать в репозиторий

2022-11-25 07:57 UTC, LexLippi commented
2. Не нашёл картинки с диаграммой БД (можно сделать средствами Idea или Dbeaver)

2022-11-25 08:02 UTC, LexLippi requested changes
Привет!

Внимательно код пока не смотрел, потому что нужна схема диаграммы БД.
Как будет, так ещё раз пробегусь. Оставил какие-то общие замечания!

Желаю удачи!!!

2022-11-25 08:02 UTC, LexLippi commented on pom.xml
> +			<groupId>org.postgresql</groupId>
А postgres тебе здесь зачем?

2022-11-25 08:02 UTC, LexLippi commented on pom.xml
> +		<dependency>
Насчет hibernate тоже не уверен, но точнее после ревью отпишусь

2022-11-25 08:02 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +import org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration;
Кажется, неипользуемый импорт.

В идее по `alt+ctrl+o` их можно выпиливать

2022-11-25 08:02 UTC, LexLippi commented on src/main/resources/schema.sql
> +DROP TABLE film, film_genre,friend, genre,like_user_film,rating,users;
Зачем вот это?)

2022-11-25 08:02 UTC, LexLippi commented on src/main/resources/schema.sql
> +    user_id integer REFERENCES users (user_id) ON DELETE CASCADE
1. `NOT NULL` ограничений не хватает, и не только здесь. Добавь везде, где поля действительно не могут быть нулевыми.
2. Странно, что где-то `INTEGER`, а где-то `integer`. Желательно одного стиля придерживаться

2022-11-26 08:02 UTC, SugarFoxy commented
> Привет!
> 
> Внимательно код пока не смотрел, потому что нужна схема диаграммы БД. Как будет, так ещё раз пробегусь. Оставил какие-то общие замечания!
> 
> Желаю удачи!!!

https://github.com/SugarFoxy/java-filmorate/tree/main/resources

2022-11-26 10:25 UTC, LexLippi requested changes
Привет!

Работа хорошая, но явно не хватает join-ов таблиц, как мне кажется, с ними можно будет обойтись без перечислений.

Желаю удачи!!!

2022-11-26 10:25 UTC, LexLippi commented on pom.xml
> +			<groupId>org.postgresql</groupId>
Эту зависимость точно надо удалить

2022-11-26 10:25 UTC, LexLippi commented on src/main/resources/schema.sql
> +    rating varchar);
Кажется, что вот это поле тоже должно быть `not null` иначе табличная запись не имеет никакого смысла, просто из идентификатора

2022-11-26 10:25 UTC, LexLippi commented on src/main/resources/schema.sql
> +    genre varchar);
Тоже должно быть `not null`

2022-11-26 10:25 UTC, LexLippi commented on src/main/resources/schema.sql
> +    status boolean);
`not null default false`

2022-11-26 10:25 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/impl/UserDbStorage.java
> +        SqlRowSet userRows = jdbcTemplate.queryForRowSet("select * from USERS where USER_ID = ?", id);
А зачем использовать такой сложный метод? Кажется, что есть более подходящие `queryForObject`, `query`, `queryForList`?

2022-11-26 10:25 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/impl/UserDbStorage.java
> +        }
Лучше не делать лишних запросов. В целом достаточно, просто обновить данные одним запросом. Да придется немного поправить сигнатуру метода, но кажется, так будет гораздо проще, удобнее и быстрее работать все методы. Это касается и методов выше

2022-11-26 10:25 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/impl/UserDbStorage.java
> +        this.friendStorage = friendStorage;
Кажется, что здесь не должно быть этого компонента

2022-11-26 10:25 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/impl/UserDbStorage.java
> +        user.setFriends(friendStorage.getAllFriendByUser(id));
Это лучше делать в service, а не здесь. Здесь непосредственное взаимодействие с одной таблицей из БД

2022-11-26 10:25 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
>      User addUser(User user);
Здесь лучше возвращать только идентификатор

2022-11-26 10:25 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +    User updateUser(User user);
этот метод лучше сделать вообще `void`

2022-11-26 10:25 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/impl/MpaDbStorage.java
> +        SqlRowSet mpaRows = jdbcTemplate.queryForRowSet("select * from RATING where RATING_ID = ?", id);
Больше не буду писать про это, чтобы не дублироваться, но кажется, что лучше заменить все `queryForRowSet` на `queryForObject`

2022-11-26 10:25 UTC, LexLippi commented on src/main/resources/schema.sql
> +    user_id integer REFERENCES users (user_id) ON DELETE CASCADE NOT NULL);
Стоит указать, что вот эти два поля в совокупности уникальны. То есть один человек не может поставить фильму два лайка

2022-11-26 10:25 UTC, LexLippi commented on src/main/resources/schema.sql
> +    film_id integer REFERENCES film (film_id) ON DELETE CASCADE NOT NULL);
Здесь тоже уникальность на пару полей, так как у фильма один жанр может быть установлен только единожды

2022-11-26 10:25 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/impl/GenreDbStorage.java
> +        String sql = String.format("select * from FILM_GENRE WHERE FILM_ID = %d", filmId);
Стоит наверное придерживаться единообразного подхода. 

1. Либо везде заранее подставлять параметры. 
2. Либо пользоваться встроенными параметрами с помощью знака вопроса. 

Лично я за второй вариант

2022-11-26 10:25 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/frends/impl/FriendDbStorage.java
> +        } catch (Exception e) {
Лучше обойтись здесь без исключений.

Исключения чаще всего нужны именно для неожиданных состояний, а здесь вполне достаточно обычного условного оператора.

Более того, исключения замедялют работу программы

2022-11-26 10:25 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    public Genre(Integer id) {
А такой зачем конструктор?

2022-11-26 10:25 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/MPA.java
> +    }
А если в БД ещё один тип добавят? Код придётся менять?
надо постараться как-то без `enum` обойтись

2022-11-26 10:25 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/RatingMpa.java
> +public enum RatingMpa {
Постараться обойтись без перечисления

2022-11-26 10:25 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/FilmDbStorage.java
> +    private final LikeStorage likeStorage;
Этих компонентов здесь быть не должно

2022-11-29 09:15 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Остался один небольшой комментарий, который надо поправить!

2022-11-29 09:15 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/impl/GenreDbStorage.java
> +        String sql = String.format("select * from FILM_GENRE WHERE FILM_ID = %d", filmId);
Может не стоит так сложно делать?
В n запросов? Можно же к таблице GENRE приджойнить таблицу GENRE, и сразу получить корректный список жанров

2022-11-30 07:22 UTC, LexLippi approved these changes
Привет, все ок, хорошая работа!

Желаю удачи в следующих спринтах!!!

2022-12-01 12:11 UTC, merged